---
experiment:
  name: mine/cgqa/
dataset:
  data_dir: cgqa
  dataset: cgqa
  splitname: compositional-split-natural
model_params:
  dropout: true
  norm: true
  nlayers: 2
  relu: false
  fc_emb: 768,1024,1200
  emb_dim: 512
  emb_init: glove
  image_extractor: resnet18
  train_only: true
  static_inp: false
training:
  batch_size: 128
  load:
  lr: 5.0e-05
  lrg: 0.001
  margin: 0.4
  max_epochs: 400
  norm_family: imagenet
  save_every: 10000
  test_batch_size: 64
  test_set: test
  topk: 1
  wd: 5.0e-05
  workers: 8
  update_features: false
  freeze_features: false
  epoch_max_margin: 100
  P_y: MLP
  latent_dim2: 2048,2048
  eta: 0.9
  smooth: 0.005
  tem: 25
